export const STUDY_PARTNERS_INPUT_CHANGED = "STUDY_PARTNERS_INPUT_CHANGED";
export const LOCATION_INPUT_CHANGED = "LOCATION_INPUT_CHANGED";

export const ADD_STUDY_PARTNER = "ADD_STUDY_PARTNER";
export const REMOVE_STUDY_PARTNER = "REMOVE_STUDY_PARTNER";
export const SET_STATE_STUDY_PARTNERS = "SET_STUDY_PARTNERS";


export const ADD_TASK = "ADD_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const TASK_UPDATE_INPUT = "TASK_UPDATE_INPUT";
export const TASK_UPDATE_URGENCY = "TASK_UPDATE_URGENCY";
export const SET_STATE_TASKS = "SET_STATE_TASKS";
export const SET_FINSHED_STATE = "SET_FINISHED_STATE";
export const TASK_UPDATE_TIME_SPENT = "TASK_UPDATE_TIME_SPENT";

export const START_SESSION = "START_SESSION";
export const FINISH_SESSION = "FINISH_SESSION";
export const SET_STATE_SESSION = "SET_SESSION";
export const END_STATE_SESSION = "END_SESSION";

export const SET_HOME_FLASH_MESSAGE = "SET_HOME_FLASH_MESSAGE";
export const REMOVE_HOME_FLASH_MESSAGE = "REMOVE_HOME_FLASH_MESSAGE";

export const SET_AUTH_FLASH_MESSAGE = "SET_AUTH_FLASH_MESSAGE";
export const REMOVE_AUTH_FLASH_MESSAGE = "REMOVE_AUTH_FLASH_MESSAGE";

export const AUTH_SUCCESS = "AUTH_START";
export const AUTH_START = "AUTH_START";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_FAIL = "AUTH_FAIL";
export const SET_USER_NAME = "SET_USER_NAME";

export const INIT_SESSIONS = "INIT_SESSIONS";