export const STUDY_PARTNERS_INPUT_CHANGED = "STUDY_PARTNERS_INPUT_CHANGED";
export const LOCATION_INPUT_CHANGED = "LOCATION_INPUT_CHANGED";


export const ADD_STUDY_PARTNER = "ADD_STUDY_PARTNER";
export const REMOVE_STUDY_PARTNER = "REMOVE_STUDY_PARTNER";


export const ADD_TASK = "ADD_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const TASK_UPDATE_INPUT = "TASK_UPDATE_INPUT";
export const TASK_UPDATE_URGENCY = "TASK_UPDATE_URGENCY";